version: "3.3"
services:
  mcqapp:
    container_name: mcqapp
    build:
      context: .
    restart: always
    environment:
      - NODE_ENV=production
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
